### ISSUE TITLE
GitHub Action should upload last.log as artifact

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/bento-action#5]
When the GitHub Action fails, we don't have a good way of debugging / diagnosing the issue. Let's upload the last.log as an action artifact.

See https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Comment by underyx** [comment]
According to https://github.com/actions/upload-artifact/blob/8eb149d680f572878047bec868c2dc7b68513bd0/action.yml#L13 the only way to upload an artifact is by adding an upload step in `.github/workflows/bento.yml`. So we cannot do this automatically, some things we could do are:

1. When bento crashes, `cat` the `last.log`
2. When bento crashes, recommend adding the artifact upload step in the workflow config
3. Add a readme section on troubleshooting recommending this step
4. Make `bento enable ci` add the upload step as well

The reason for the first-party only uploads is probably that artifact storage above the free tier costs $0.25 USD per GB of storage per month[0].

@nbrahms which ones of the four should we do? Any further ideas?

[0]: https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by nbrahms** [comment]
Probably the easiest is to detect the github-action environment variable, and echo the log on a crash?

**Comment by underyx** [comment]
No env var detection needed, the `entrypoint.sh` can just echo the log on its own, that'll only run in the action.

**Comment by nbrahms** [comment]
Perfect 👌

**Comment by underyx** [comment]
See what it looks like here: https://github.com/underyx/flask-todomvc/runs/492485001
